### ISSUE TITLE
"System.NullReferenceException: Object reference not set to an instance of an object." While using qHud

### ISSUE THREAD

**Issue by Ludw1g** [vmv/qHUD#2]
Hey, I've started getting this Error every few maps, Not sure if I should've posted this on OC or here.
I tried to play around with the settings turning off features to find what's broken but it still happened with everything off. Using a clean install with Windows 10.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at qHUD.Poe.Elements.ItemOnGroundTooltip.get_TooltipUI()
   at qHUD.Poe.Elements.InventoryItemIcon.GetToolTipType()
   at qHUD.Poe.Elements.InventoryItemIcon.get_ToolTipType()
   at qHUD.Poe.Elements.InventoryItemIcon.get_Tooltip()
   at qHUD.Hud.ItemTooltips.ItemTooltipPlugin.Render()
   at qHUD.Hud.ExternalOverlay.<>c.<OnRender>b__15_0(IPlugin x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at qHUD.Hud.ExternalOverlay.OnRender()
   at qHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at qHUD.Hud.UI.Graphics.RenderLoop()
   at qHUD.Hud.ExternalOverlay.<OnLoad>b__14_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at qHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by Ludw1g** [comment]
Also something I have noticed: Essence of Corruption doesn't get shown in preload alerts.

**Comment by vmv** [comment]
I was lazy and copy/pasted from main hud all updates and didn't cared so much for the code. If i can't find what's wrong in the code, i may ask TehCheat to help me.
Here is an atempt for a fix..just the exe file: 
[qHUD.zip](https://github.com/vmv/qHUD/files/473967/qHUD.zip)

These are all the essences i could find in the Content:
0,Hatred
1,Woe
2,Greed
3,Contempt
4,Sorrow
5,Anger
6,Torment
7,Fear
8,Suffering
9,Rage
10,Wrath
11,Doubt
12,Anguish
13,Loathing
14,Spite
15,Zeal
16,Misery
17,Dread
18,Scorn
19,Envy
20,Hysteria
21,Insanity
22,Horror
23,Delirium
24,NotEssence

Which one is of Corruption ?

**Comment by vmv** [comment]
I have made some changes, played for an hour or so, and i haven't got any error so far.
But i can't be sure because i'm using a low level char and the error is caused by some items on ground...
You can download the last release again, it's updated, and see if it's happening anymore.

**Comment by Ludw1g** [comment]
"24,NotEssence" is most likely the corruption one if it is in the list.
I'll download it and try to report back if I find out what's causing the issue if it is still happening.

**Comment by vmv** [comment]
I think this has been fixed. Never happened again since last update.
